name: flet_audio_recorder
description: Flet AudioRecorder control
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet-audio-recorder/src/flutter/flet_audio_recorder
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  record: 6.0.0

  # flet: ^0.25.2
  flet:
    git:
      path: packages/flet
      ref: v1
      url: https://github.com/flet-dev/flet.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0